# Generated by Django 5.2.7 on 2025-12-16 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='รอบที่')),
                ('match_number', models.PositiveIntegerField(verbose_name='นัดที่')),
                ('status', models.CharField(choices=[('scheduled', 'กำหนดการ'), ('in_progress', 'กำลังแข่งขัน'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='scheduled', max_length=20, verbose_name='สถานะ')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่กำหนด')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเริ่ม')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเสร็จ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'นัดแข่งขัน',
                'verbose_name_plural': 'นัดแข่งขัน',
                'ordering': ['round_number', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField(default=dict, verbose_name='ข้อมูลผลการแข่งขัน')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาบันทึก')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='sports.match', verbose_name='นัด')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_match_results', to=settings.AUTH_USER_MODEL, verbose_name='บันทึกโดย')),
            ],
            options={
                'verbose_name': 'ผลการแข่งขัน',
                'verbose_name_plural': 'ผลการแข่งขัน',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อกีฬา')),
                ('template_config', models.JSONField(default=dict, verbose_name='Template Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_types', to='core.organization', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'ชนิดกีฬา',
                'verbose_name_plural': 'ชนิดกีฬา',
                'ordering': ['name'],
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อการแข่งขัน')),
                ('format', models.CharField(choices=[('round_robin', 'Round Robin'), ('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination')], max_length=50, verbose_name='รูปแบบ')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('active', 'กำลังแข่งขัน'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='draft', max_length=20, verbose_name='สถานะ')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='ตั้งค่าเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.event', verbose_name='กิจกรรม')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.organization', verbose_name='หน่วยงาน')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='sports.sporttype', verbose_name='ชนิดกีฬา')),
            ],
            options={
                'verbose_name': 'การแข่งขัน',
                'verbose_name_plural': 'การแข่งขัน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sports.tournament', verbose_name='การแข่งขัน'),
        ),
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.JSONField(blank=True, default=dict, verbose_name='คะแนน')),
                ('result', models.CharField(blank=True, max_length=50, verbose_name='ผลการแข่งขัน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_teams', to='sports.match', verbose_name='นัด')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to='teams.team', verbose_name='ทีม')),
            ],
            options={
                'verbose_name': 'ทีมในนัด',
                'verbose_name_plural': 'ทีมในนัด',
                'ordering': ['created_at'],
                'unique_together': {('match', 'team')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'round_number', 'match_number')},
        ),
    ]
