# Generated by Django 5.2.7 on 2025-12-16 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อการจับสลาก')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('rules', models.JSONField(blank=True, default=dict, verbose_name='กติกา')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_events', to='core.event', verbose_name='กิจกรรม')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_events', to='core.organization', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'การจับสลาก',
                'verbose_name_plural': 'การจับสลาก',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='รอบที่')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อรางวัล')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('rules', models.JSONField(blank=True, default=dict, verbose_name='กติกา')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raffle_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='raffle.raffleevent', verbose_name='การจับสลาก')),
            ],
            options={
                'verbose_name': 'ของรางวัล',
                'verbose_name_plural': 'ของรางวัล',
                'ordering': ['round_number', 'name'],
                'unique_together': {('raffle_event', 'round_number', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RaffleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=100, verbose_name='Seed value')),
                ('rule_snapshot', models.JSONField(default=dict, verbose_name='Snapshot ของกติกา')),
                ('result', models.JSONField(default=dict, verbose_name='ผลการจับสลาก')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='raffle.prize', verbose_name='รางวัล')),
                ('raffle_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='raffle.raffleevent', verbose_name='การจับสลาก')),
            ],
            options={
                'verbose_name': 'Raffle Log',
                'verbose_name_plural': 'Raffle Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RaffleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่ถูกเลือก')),
                ('seed_value', models.CharField(blank=True, max_length=100, verbose_name='Seed value สำหรับตรวจสอบ')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_selections', to='teams.participant', verbose_name='ผู้เข้าร่วม')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_participants', to='raffle.prize', verbose_name='รางวัล')),
            ],
            options={
                'verbose_name': 'ผู้ถูกเลือก',
                'verbose_name_plural': 'ผู้ถูกเลือก',
                'ordering': ['selected_at'],
                'unique_together': {('prize', 'participant')},
            },
        ),
    ]
