# Generated by Django 5.2.7 on 2025-12-17 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleEligibleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_raffle_eligibilities', to=settings.AUTH_USER_MODEL, verbose_name='เพิ่มโดย')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_eligibilities', to='teams.participant', verbose_name='ผู้เข้าร่วม')),
                ('raffle_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_participants', to='raffle.raffleevent', verbose_name='การจับสลาก')),
            ],
            options={
                'verbose_name': 'ผู้มีสิทธิ์รับรางวัล',
                'verbose_name_plural': 'ผู้มีสิทธิ์รับรางวัล',
                'ordering': ['created_at'],
                'unique_together': {('raffle_event', 'participant')},
            },
        ),
    ]
