# Generated by Django 5.2.7 on 2025-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0002_raffleeligibleparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleeligibleparticipant',
            name='is_opted_out',
            field=models.BooleanField(default=True, help_text='ถ้าเปิด หมายความว่าสละสิทธิ์รับรางวัล', verbose_name='สละสิทธิ์'),
        ),
        migrations.AddField(
            model_name='raffleeligibleparticipant',
            name='opt_out_reason',
            field=models.TextField(blank=True, verbose_name='เหตุผลในการตัดสิทธิ'),
        ),
        migrations.AddField(
            model_name='raffleevent',
            name='no_repeat_prize',
            field=models.BooleanField(default=False, help_text='ถ้าเปิด ผู้ที่ได้รับรางวัลแล้วจะไม่ถูกเลือกอีก', verbose_name='ไม่รับรางวัลซ้ำ'),
        ),
    ]
