# Generated by Django 5.2.7 on 2025-12-16 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อ')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='ข้อมูลเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='core.department', verbose_name='หน่วยงาน')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.event', verbose_name='กิจกรรม')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.organization', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'ผู้เข้าร่วม',
                'verbose_name_plural': 'ผู้เข้าร่วม',
                'ordering': ['name'],
                'unique_together': {('org', 'event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100, verbose_name='ชื่อสี')),
                ('color_code', models.CharField(default='#000000', max_length=7, verbose_name='รหัสสี (HEX)')),
                ('max_members', models.PositiveIntegerField(blank=True, null=True, verbose_name='จำนวนสมาชิกสูงสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.event', verbose_name='กิจกรรม')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.organization', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'ทีม',
                'verbose_name_plural': 'ทีม',
                'ordering': ['color_name'],
                'unique_together': {('org', 'event', 'color_name')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='ล็อค (ไม่ให้ย้าย)')),
                ('is_moved', models.BooleanField(default=False, verbose_name='ถูกย้าย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moved_from_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_members', to='teams.team', verbose_name='ย้ายมาจากทีม')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='teams.participant', verbose_name='ผู้เข้าร่วม')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team', verbose_name='ทีม')),
            ],
            options={
                'verbose_name': 'สมาชิกทีม',
                'verbose_name_plural': 'สมาชิกทีม',
                'ordering': ['created_at'],
                'unique_together': {('team', 'participant')},
            },
        ),
    ]
