# Generated by Django 5.2.7 on 2025-12-16 13:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อหน่วยงาน')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code must be alphanumeric with - or _', regex='^[a-zA-Z0-9_-]+$')], verbose_name='รหัสหน่วยงาน')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='ตั้งค่าเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'หน่วยงาน',
                'verbose_name_plural': 'หน่วยงาน',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อกิจกรรม')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('start_date', models.DateTimeField(verbose_name='วันที่เริ่ม')),
                ('end_date', models.DateTimeField(verbose_name='วันที่สิ้นสุด')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('active', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='draft', max_length=20, verbose_name='สถานะ')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='ตั้งค่าเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.organization', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'กิจกรรม',
                'verbose_name_plural': 'กิจกรรม',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ModuleRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('teams', 'Color Team Management'), ('raffle', 'Raffle System'), ('sports', 'Sports Day System')], max_length=50, verbose_name='Module')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='ตั้งค่าเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_registries', to='core.organization', verbose_name='หน่วยงาน (null = global)')),
            ],
            options={
                'verbose_name': 'Module Registry',
                'verbose_name_plural': 'Module Registries',
                'ordering': ['module', 'org'],
                'unique_together': {('module', 'org')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อหน่วยงาน')),
                ('code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Code must be alphanumeric with - or _', regex='^[a-zA-Z0-9_-]+$')], verbose_name='รหัสหน่วยงาน')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.organization', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'หน่วยงาน',
                'verbose_name_plural': 'หน่วยงาน',
                'ordering': ['name'],
                'unique_together': {('org', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'สร้าง'), ('update', 'แก้ไข'), ('delete', 'ลบ'), ('view', 'ดู'), ('import', 'นำเข้า'), ('export', 'ส่งออก'), ('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ')], max_length=20, verbose_name='การกระทำ')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='การเปลี่ยนแปลง')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.organization', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['org', '-timestamp'], name='core_auditl_org_id_c5f54d_idx'), models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'), models.Index(fields=['model', 'object_id'], name='core_auditl_model_cea205_idx')],
            },
        ),
    ]
