# Generated by Django 5.2.7 on 2025-12-16 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.CharField(blank=True, default='/images/login-bg.png', help_text='Path to background image (e.g., /images/login-bg.png)', max_length=500, verbose_name='Background Image Path')),
                ('show_logo', models.BooleanField(default=True, verbose_name='แสดง Logo')),
                ('logo_text', models.CharField(blank=True, default='N', help_text='ตัวอักษรที่แสดงใน logo (ถ้าไม่มี logo image)', max_length=10, verbose_name='Logo Text')),
                ('logo_image', models.CharField(blank=True, help_text='Path to logo image (ถ้ามี, จะใช้แทน logo text)', max_length=500, verbose_name='Logo Image Path')),
                ('title', models.CharField(default='NRSport', max_length=200, verbose_name='หัวข้อหลัก')),
                ('subtitle', models.CharField(default='ระบบกลางสำหรับจัดกิจกรรมหน่วยงาน', max_length=500, verbose_name='คำอธิบาย')),
                ('overlay_opacity', models.FloatField(default=0.5, help_text='ความเข้มของ overlay (0.0 - 1.0)', verbose_name='Overlay Opacity')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_settings', to='core.organization', verbose_name='หน่วยงาน (null = global)')),
            ],
            options={
                'verbose_name': 'ตั้งค่าหน้า Login',
                'verbose_name_plural': 'ตั้งค่าหน้า Login',
                'ordering': ['org', '-created_at'],
                'unique_together': {('org',)},
            },
        ),
    ]
