# Generated by Django 5.2.7 on 2025-12-17 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginpagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Code must be alphanumeric with - or _', regex='^[a-zA-Z0-9_-]+$')], verbose_name='รหัสแผนก'),
        ),
    ]
